spc:
  enabled: false

objects: |
     array:  
        - |
          objectType: secret              # object types: secret, key, or cert  
        

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 75
resources:
  requests:
    memory: "200Mi"
  limits:
    memory: "512Mi"

env:
  - name: DATABASE_URL
    value: "postgresql://7x_nls_stg:ToqpIUHeb%40uug8kx@psql-shared-test-aen-db.postgres.database.azure.com:6432/7x_nls_stg?sslmode=verify-ca"
  - name: AZURE_AI_ENDPOINT
    value: "https://altha-mmdafubs-eastus2.services.ai.azure.com/anthropic/v1/messages"
  - name: AZURE_AI_KEY
    value: "ALg3BuKQfpuWpA9xZRcLF1xooaJzN2g9Ntap1xMMAsMI6U1GDl4uJQQJ99CCACHYHv6XJ3w3AAAAACOGEJtt"
  - name: AZURE_AI_DEPLOYMENT
    value: "claude-sonnet-4-5"
  - name: RESEND_API_KEY
    value: "re_hn64mAGa_J464ngAwGmzFkGvdzguCF5dr"
  - name: ADMIN_USERNAME
    value: "admin"
  - name: ADMIN_PASSWORD
    value: "CHANGE_ME"
  - name: NXN_PASSWORD
    value: "nxn"
  - name: EMU_PASSWORD
    value: "emu"