{{- if .Values.spc.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "project.fullname" . }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.managedidentityid }} # Setting this to use workload identity
    keyvaultName: {{ .Values.kvname }}      
    cloudName: ""                         
    objects:  {{- .Values.objects | toYaml | indent 1 }}                 
    tenantId: "c83314fa-75af-4236-8242-8305919cb91f"   
{{- end }}    